== User Group
=== Create / Post Collection

==== Description
Create a UserRole

/api/user_roles, method=Post

===== Post Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,    Type,      Required, Comment
code,        string,    true,     "String value of uuid"
name,        string,    true,     "String value"
roleName,    string,    false,    "IRI value of Customer"
description, string,    false,    "String value"

|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::post_collection_management_rules.csv[]
|===

==== Messages

[cols=",~",format="csv",options="header"]
|===
ID, Content
include::post_collection_messages.csv[]
|===

=== Read / Get Collection

==== Description
Retrieve a list of UserGroup
/api/user_roles, method=Get

==== Request Parameters

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type,   Required, Comment
page,       number, false,    "Page index, from 0"
limit,      number, false,    "Items per page"
roleName,   string, false,    "Filter by 'userRole.name LIKE %name%' "
name,       string, false,    "Filter by customer name "
code,       string, false,    "Search on code"
createdAt,  date,   false,    "Search on date of creation"
updatedAt,  date,   false,    "Search on date of update"
|===



==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_collection_management_rules.csv[]
|===

=== Read / Get Item

==== Description
Retrieve a UserGroup
/api/user_roles/{code}, method=Get

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_item_management_rules.csv[]
|===

<<<

=== Patch

==== Description
/api/user_groups/{code}, method=Patch

===== Body Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,    Type,      Required, Comment
name,        string,    false,    "String value"
roleName,    string,    false,    "IRI value of Customer"
description, string,    false,    "String value"

|===

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_management_rules.csv[]
|===

<<<


=== Update / Put Item

==== Description
Update a UserGroup
/api/user_roles/{code}, method=Put

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

===== Put Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,    Type,      Required, Comment
name,        string,    false,    "String value"
roleName,    string,    false,    "IRI value of Customer"
description, string,    false,    "String value"

|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::put_item_management_rules.csv[]
|===

=== Delete / Delete Item

==== Description
Delete a UserGroup
/api/user_roles/{code}, method=Delete

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::delete_item_management_rules.csv[]
|===
