== DeviceModelOutput

=== Create / Post Collection

==== Description
Create a DeviceModelOutput

/api/device_model_outputs, method=Post

===== Post Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,    Type,      Required, Comment
code,        string,    true,     "String value of uuid"
name,        string,    true,     "String value"
description, string,    false,    "String value"
model,       IRI,       true,     "IRI value of Device Model"
number,      integer,   true,     "Integer value (number of the output in the Device Model)"

|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::post_collection_management_rules.csv[]
|===

==== Messages

[cols=",~",format="csv",options="header"]
|===
ID, Content
include::post_collection_messages.csv[]
|===

<<<

=== Read / Get Collection

==== Description
Retrieve a list of DeviceModelOutput
/api/device_model_outputs, method=Get

==== Request Parameters

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type,    Required, Comment
page,       number,  false,    "Page index, from 0"
limit,      number,  false,    "Items per page"
name,       string,  false,    "Filter by 'deviceDiagnostic.name LIKE %name%'"
createdAt,  date,    false,    "Search on date of creation"
updatedAt,  date,    false,    "Search on date of update"
number,     integer, false,    "Search on number"

|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_collection_management_rules.csv[]
|===

<<<


=== Read / Get Item

==== Description
Retrieve a DeviceModelOutput
/api/device_model_outputs/{code}, method=Get

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_item_management_rules.csv[]
|===

<<<

=== Patch

==== Description
/api/device_model_outputs/{code}, method=Patch

===== Body Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,    Type,      Required, Comment
name,        string,    false,    "String value"
description, string,    false,    "String value"
model,       IRI,       false,    "IRI value of Device Model"
number,      integer,   false,    "Integer value (number of the output in the Device Model)"
|===

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_management_rules.csv[]
|===

<<<


=== Update / Put Item

==== Description
Update a DeviceModelOutput
/api/device_model_outputs/{code}, method=Put

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

===== Put Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,    Type,      Required, Comment
name,        string,    false,     "String value"
description, string,    false,    "String value"
model,       IRI,       false,     "IRI value of Device Model"
number,      integer,   false,     "Integer value (number of the output in the Device Model)"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::put_item_management_rules.csv[]
|===

<<<


=== Delete / Delete Item

==== Description
Delete a DeviceModelOutput
/api/device_model_outputs/{code}, method=Delete

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::delete_item_management_rules.csv[]
|===
