== Tags
=== Create / Post Collection

==== Description
Create a Tag

/api/tags, method=Post

===== Post Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,    Type,      Required, Comment
code,        string,    true,     "String value of uuid"
name,        string,    true,     "String value"
description, object,    false,    "String value"
tagGroup,    IRI,       true,     "IRI value of TagGroup"

|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::post_collection_management_rules.csv[]
|===

==== Messages

[cols=",~",format="csv",options="header"]
|===
ID, Content
include::post_collection_messages.csv[]
|===


<<<

=== Read / Get Collection

==== Description
Retrieve a list of Tag
/api/tags, method=Get

==== Request Parameters

[cols=",,,~",format="csv",options="header"]
|===
Parameters,    Type,    Required, Comment
page,          number,  false,    "Page index, from 0"
limit,         number,  false,    "Items per page"
name,          string,  false,    "Filter by 'deviceDiagnostic.name LIKE %name%'"
createdAt,     date,    false,    "Search on date of creation"
updatedAt,     date,    false,    "Search on date of update"
tagGroup.name, string,  false,    "Search on userGroup code"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_collection_management_rules.csv[]
|===

<<<

=== Read / Get Item

==== Description
Retrieve a Tag
/api/tags/{code}, method=Get

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_item_management_rules.csv[]
|===

<<<

=== Patch

==== Description
/api/tags/{code}, method=Patch

===== Body Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,    Type,      Required, Comment
name,        string,    false,     "String value"
description, object,    false,    "String value"
tagGroup,    IRI,       false,     "IRI value of TagGroup"
|===

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_management_rules.csv[]
|===

<<<

=== Update / Put Item

==== Description
Update a Tag
/api/tags/{code}, method=Put

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

===== Put Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,    Type,      Required, Comment
name,        string,    false,     "String value"
description, object,    false,    "String value"
tagGroup,    IRI,       false,     "IRI value of TagGroup"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::put_item_management_rules.csv[]
|===

=== Delete / Delete Item

==== Description
Delete a Tag
/api/tags/{code}, method=Delete

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::delete_item_management_rules.csv[]
|===
