== Tag Group
=== Create / Post Collection

==== Description
Create a TagGroup

/api/tag_groups, method=Post

===== Post Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,  Type,      Required, Comment
code,      string,    true,     "String value of uuid"
name,      string,    true,     "String value"
url,       string,    true,     "Valid url"
enabled,   boolean,   false,    "Enabled status"
userGroup, IRI,       false,    "IRI value of UserGroup, if null, the Tag Group will be available for all user groups"
options,   object,    true,     "An object with four boolean fields: `multiValueAllowed`,`required`, `filterable`, `newValueAllowed` "
target,    IRI,       true,     "IRI value of Tag Target"
tags,      IRI array, false,    "IRI value of Tag Target"

|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::post_collection_management_rules.csv[]
|===

==== Messages

[cols=",~",format="csv",options="header"]
|===
ID, Content
include::post_collection_messages.csv[]
|===


<<<

=== Read / Get Collection

==== Description
Retrieve a list of TagGroup
/api/tag_groups, method=Get

==== Request Parameters

[cols=",,,~",format="csv",options="header"]
|===
Parameters,      Type,    Required, Comment
page,            number,  false,    "Page index, from 0"
limit,           number,  false,    "Items per page"
name,            string,  false,    "Filter by 'deviceDiagnostic.name LIKE %name%'"
createdAt,       date,    false,    "Search on date of creation"
updatedAt,       date,    false,    "Search on date of update"
userGroup.code,  string,  false,    "Search on userGroup code"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_collection_management_rules.csv[]
|===

<<<

=== Read / Get Item

==== Description
Retrieve a TagGroup
/api/tag_groups/{code}, method=Get

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_item_management_rules.csv[]
|===

<<<

=== Patch

==== Description
/api/tag_groups/{code}, method=Patch

===== Body Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,  Type,      Required, Comment
name,      string,    true,     "String value"
url,       string,    true,     "Valid url"
enabled,   boolean,   false,    "Enabled status"
userGroup, IRI,       false,    "IRI value of UserGroup, if null, the Tag Group will be available for all user groups"
options,   object,    true,     "An object with four boolean fields: `multiValueAllowed`,`required`, `filterable`, `newValueAllowed` "
target,    IRI,       true,     "IRI value of Tag Target"
tags,      IRI array, false,    "IRI value of Tag Target"
|===

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_management_rules.csv[]
|===

<<<

=== Update / Put Item

==== Description
Update a TagGroup
/api/tag_groups/{code}, method=Put

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

===== Put Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,  Type,      Required, Comment
code,      string,    true,     "String value of uuid"
name,      string,    true,     "String value"
url,       string,    true,     "Valid url"
enabled,   boolean,   false,    "Enabled status"
userGroup, IRI,       false,    "IRI value of UserGroup, if null, the Tag Group will be available for all user groups"
options,   object,    true,     "An object with four boolean fields: `multiValueAllowed`,`required`, `filterable`, `newValueAllowed` "
target,    IRI,       true,     "IRI value of Tag Target"
tags,      IRI array, false,    "IRI value of Tag Target"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::put_item_management_rules.csv[]
|===

=== Delete / Delete Item

==== Description
Delete a TagGroup
/api/tag_groups/{code}, method=Delete

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::delete_item_management_rules.csv[]
|===
