== Platform
=== Create / Post Collection

==== Description
Create a Platform

/api/platforms, method=Post

===== Post Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,     Type,    Required, Comment
code,         string,  true,     "String value of uuid"
name,         string,  true,     "String value"
description,  string,  false,    "String value"
userGroup,    IRI,     true,     "IRI value of UserGroup"
apiHttpUrl,   string,  false,    "String value"
apiHttpProxy, string,  false,    "String value"
apiSocketUrl, string,  true,     "String value"
color,        string,  true,     "Hexa string value of the color, without the #"
enabled,      boolean, false,     "Enabled status, default to true"
tagsData,     json,    false,    "An object with Tag Groups IRI with arrays of Tags IRI"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::post_collection_management_rules.csv[]
|===

==== Messages

[cols=",~",format="csv",options="header"]
|===
ID, Content
include::post_collection_messages.csv[]
|===


=== Read / Get Collection

==== Description
Retrieve a list of Platform
/api/platforms, method=Get

==== Request Parameters

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
page,  number, false, "Page index, from 0"
limit, number, false, "Items per page"
name, string, false, "Filter by 'videoStream.name LIKE %name%' "
enabled, boolean, false, "Filter by enabled status"
devices.tags.name, string, false, "Search by tag name of devices"

|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_collection_management_rules.csv[]
|===

=== Read / Get Item

==== Description
Retrieve a Platform
/api/platforms/{code}, method=Get

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_item_management_rules.csv[]
|===


<<<

=== Patch

==== Description
/api/customers/{code}, method=Patch

===== Body Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,    Type,    Required, Comment
name,        string,  true,     "String value"
description, string,  false,    "Description"
enabled,     boolean, false,    "Enabled status, default to true"
|===

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_management_rules.csv[]
|===

<<<

=== Patch enable

==== Description
/api/customers/{code}/enable, method=Patch


[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_enable_management_rules.csv[]
|===

<<<

=== Patch disable

==== Description
/api/customers/{code}/disable, method=Patch

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_enable_management_rules.csv[]
|===

<<<

=== Patch name

==== Description
/api/customers/{code}/name, method=Patch

===== Body Data (json)
At least one of the fields must be provided.
[cols=",,,~",format="csv",options="header"]
|===
Property, Type, Required, Comment
name, string, false, "String value"
description, string, false, "String value"

|===

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_enable_management_rules.csv[]
|===

<<<




=== Update / Put Item

==== Description
Update a Platform
/api/platforms/{code}, method=Put

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

===== Put Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,     Type,    Required, Comment
name,         string,  true,     "String value"
description,  string,  false,    "String value"
apiHttpUrl,   string,  false,    "String value"
apiHttpProxy, string,  false,    "String value"
apiSocketUrl, string,  true,     "String value"
color,        string,  true,     "Hexa string value of the color, without the #"
enabled,      boolean, false,     "Enabled status, default to true"
tagsData,     json,    false,    "An object with Tag Groups IRI with arrays of Tags IRI"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::put_item_management_rules.csv[]
|===

=== Delete / Delete Item

==== Description
Delete a Platform
/api/platforms/{code}, method=Delete

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::delete_item_management_rules.csv[]
|===
