== DeviceOutput

=== Create / Post Collection

==== Description
Create a DeviceOutput

/api/device_outputs, method=Post

===== Post Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,            Type,      Required, Comment
code,                string,    true,     "String value of uuid"
device,              IRI,       true,     "IRI value of Device"
modelOutput,         IRI,       true,     "IRI value of ModelOutput"
videoStream,         IRI,       false,    "IRI value of VideoStream"
modelOutput,         IRI,       false,    "IRI value of ModelOutput"
screen,              IRI,       false,    "IRI value of Screen"
templateModelOutput, IRI,       false,    "IRI value of TemplateModelOutput"

|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::post_collection_management_rules.csv[]
|===

==== Messages

[cols=",~",format="csv",options="header"]
|===
ID, Content
include::post_collection_messages.csv[]
|===

<<<

=== Read / Get Collection

==== Description
Retrieve a list of DeviceOutput
/api/device_outputs, method=Get

==== Request Parameters

[cols=",,,~",format="csv",options="header"]
|===
Parameters,                     Type,    Required, Comment
page,                           number,  false,    "Page index, from 0"
limit,                          number,  false,    "Items per page"
name,                           string,  false,    "Filter by 'deviceDiagnostic.name LIKE %name%'"
search_global,                  string,  false,    "Search on multiple fields"
enabled,                        boolean, false,    "Search on enabled status"
code,                           string,  false,    "Search on code"
createdAt,                      date,    false,    "Search on date of creation"
updatedAt,                      date,    false,    "Search on date of update"
device.macAddress,              string,  false,    "Search on device macAddress"
device.enabled,                 boolean, false,    "Search on enabled status of Device"
device.serialNumber,            string,  false,    "Search on device serialNumber"
device.name,                    string,  false,    "Search on device name"
device.site.externalId,         string,  false,    "Search on device site externalId"
device.site.name,               string,  false,   "Search on device site name"
device.tags.name,               string,  false,   "Search on device tags name"
device.status.name,             string,  false,   "Search on device status name"
device.model.name,              string,  false,   "Search on device model name"
device.userGroup.customer.name, string,  false,    "Search on device usergroup customer name"
device.userGroup.name,          string,  false,   "Search on device usergroup name"
device.network.name,            string,  false,   "Search on device network name"
device.platform.name,           string,  false,   "Search on device platform name"
exists[device.site],            boolean, false,   "Filter by no device site (false) or with a device site (true)"
exists[videoStream],            boolean, false,   "Filter by no videoStream (false) or with a videoStream (true)"
modelOutput.name,               string,  false,    "Search on modelOutput name"
videoStream.name,               string,  false,    "Search on videoStream name"
videoOverlay.name,              string,  false,    "Search on videoOverlay name"
screen.name,                    string,  false,    "Search on screen name"
templateModelOutput.name,       string,  false,    "Search on templateModelOutput name"

|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_collection_management_rules.csv[]
|===

<<<


=== Read / Get Item

==== Description
Retrieve a DeviceOutput
/api/device_outputs/{code}, method=Get

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_item_management_rules.csv[]
|===

<<<

=== Patch

==== Description
/api/device_outputs/{code}, method=Patch

===== Body Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,            Type,      Required, Comment
device,              IRI,       false,    "IRI value of Device"
modelOutput,         IRI,       false,    "IRI value of ModelOutput"
videoStream,         IRI,       false,    "IRI value of VideoStream"
modelOutput,         IRI,       false,    "IRI value of ModelOutput"
screen,              IRI,       false,    "IRI value of Screen"
templateModelOutput, IRI,       false,    "IRI value of TemplateModelOutput"
|===

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_management_rules.csv[]
|===

<<<


=== Update / Put Item

==== Description
Update a DeviceOutput
/api/device_outputs/{code}, method=Put

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

===== Put Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,            Type,      Required, Comment
device,              IRI,       false,    "IRI value of Device"
modelOutput,         IRI,       false,    "IRI value of ModelOutput"
videoStream,         IRI,       false,    "IRI value of VideoStream"
modelOutput,         IRI,       false,    "IRI value of ModelOutput"
screen,              IRI,       false,    "IRI value of Screen"
templateModelOutput, IRI,       false,    "IRI value of TemplateModelOutput"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::put_item_management_rules.csv[]
|===

<<<


=== Delete / Delete Item

==== Description
Delete a DeviceOutput
/api/device_outputs/{code}, method=Delete

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::delete_item_management_rules.csv[]
|===
