== EntityDisplayCustomization

=== Create / Post Collection

==== Description
Create a EntityDisplayCustomization

/api/entity_display_customizations, method=Post

===== Post Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,        Type,      Required, Comment
code,            string,    true,     "String value of uuid"
name,            string,    true,     "String value"
description,     string,    false,    "String value"
columns,         array,     false,    "An array of ColumnDefinition (label, propertyName, propertyType)"
entityClassName, string,    true,     "String value of the class name of the entity"
isDefault,       boolean,   true,     "Default status"
owner,           IRI,       true,     "IRI value of a valid User"
sharedWith,      IRI,       false,    "IRI value of a valid UserGroup"

|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::post_collection_management_rules.csv[]
|===

==== Messages

[cols=",~",format="csv",options="header"]
|===
ID, Content
include::post_collection_messages.csv[]
|===

<<<

=== Read / Get Collection

==== Description
Retrieve a list of EntityDisplayCustomization
/api/entity_display_customizations, method=Get

==== Request Parameters

[cols=",,,~",format="csv",options="header"]
|===
Parameters,      Type,    Required, Comment
page,            number,  false,    "Page index, from 0"
limit,           number,  false,    "Items per page"
name,            string,  false,    "Filter by 'deviceDiagnostic.name LIKE %name%'"
createdAt,       date,    false,    "Search on date of creation"
updatedAt,       date,    false,    "Search on date of update"
number,          integer, false,    "Search on number"
entityClassName, string,  false,    "Search on class name of entity"
owner.code,      string,  false,    "Search on code of User for this entity"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_collection_management_rules.csv[]
|===

<<<


=== Read / Get Item

==== Description
Retrieve a EntityDisplayCustomization
/api/entity_display_customizations/{code}, method=Get

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_item_management_rules.csv[]
|===

<<<

=== Patch

==== Description
/api/entity_display_customizations/{code}, method=Patch

===== Body Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,        Type,      Required, Comment
name,            string,    false,    "String value"
description,     string,    false,    "String value"
columns,         array,     false,    "An array of ColumnDefinition (label, propertyName, propertyType)"
isDefault,       boolean,   false,    "Default status"
sharedWith,      IRI,       false,    "IRI value of a valid UserGroup"
|===

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_management_rules.csv[]
|===

<<<


=== Update / Put Item

==== Description
Update a EntityDisplayCustomization
/api/entity_display_customizations/{code}, method=Put

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

===== Put Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,        Type,      Required, Comment
name,            string,    false,    "String value"
description,     string,    false,    "String value"
columns,         array,     false,    "An array of ColumnDefinition (label, propertyName, propertyType)"
isDefault,       boolean,   false,    "Default status"
sharedWith,      IRI,       false,    "IRI value of a valid UserGroup"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::put_item_management_rules.csv[]
|===

<<<


=== Delete / Delete Item

==== Description
Delete a EntityDisplayCustomization
/api/entity_display_customizations/{code}, method=Delete

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::delete_item_management_rules.csv[]
|===
