== User
=== Create / Post Collection

==== Description
Create a User

/api/users, method=Post

===== Post Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,      Type,      Required, Comment
code,          string,    true,    "String value of uuid"
groups,        IRI array, true,     "An array of IRI value of UserGroup"
userRoles,     IRI array, false,    "An array of IRI values of Network"
plainPassword, string,    true,     "String value"
username,      string,    true,     "String value. Must be unique."
email,         string,    true,     "String value. Must be unique."

|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::post_collection_management_rules.csv[]
|===

==== Messages

[cols=",~",format="csv",options="header"]
|===
ID, Content
include::post_collection_messages.csv[]
|===

=== Read / Get Collection

==== Description
Retrieve a list of User
/api/users, method=Get

==== Request Parameters

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type,     Required, Comment
page,       number,   false,    "Page index, from 0"
limit,      number,   false,    "Items per page"
username,   string,   false,    "Filter by 'user.name LIKE %name%'"
email,      string,   false,    "Search on userGroup name"
code,       string,   false,    "Search on code"
createdAt,  date,     false,    "Search on date of creation"
updatedAt,  date,     false,    "Search on date of update"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_collection_management_rules.csv[]
|===

=== Read / Get Item

==== Description
Retrieve a User
/api/users/{code}, method=Get

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_item_management_rules.csv[]
|===

<<<

=== Patch

==== Description
/api/users/{code}, method=Patch

===== Body Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,      Type,      Required, Comment
groups,        IRI array, false,    "An array of IRI value of UserGroup"
userRoles,     IRI array, false,    "An array of IRI values of Network"
plainPassword, string,    false,    "String value"
username,      string,    false,    "String value. Must be unique."
email,         string,    false,    "String value. Must be unique."
|===

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_management_rules.csv[]
|===

<<<

=== Patch set is super admin

==== Description
/api/users/{code}/set_is_super_admin, method=Patch


[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_unset_is_super_admin_management_rules.csv[]
|===

<<<

=== Patch unset is super admin

==== Description
/api/users/{code}/unset_is_super_admin, method=Patch

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_unset_is_super_admin_management_rules.csv[]
|===

<<<


=== Update / Put Item

==== Description
Update a User
/api/users/{code}, method=Put

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

===== Put Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property, Type, Required, Comment
enabled,       boolean,   false,    "String value"
groups,        IRI array, true,     "An array of IRI value of UserGroup"
userRoles,     IRI array, false,    "An array of IRI values of Network"
plainPassword, string,    true,     "String value"
username,      string,    true,     "String value. Must be unique."
email,         string,    true,     "String value. Must be unique."
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::put_item_management_rules.csv[]
|===

=== Delete / Delete Item

==== Description
Delete a User
/api/users/{code}, method=Delete

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::delete_item_management_rules.csv[]
|===
