== Network
=== Create / Post Collection

==== Description
Create a Network

/api/networks, method=Post

===== Post Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,    Type,    Required, Comment
code,        string,  true,     "String value of uuid"
name,        string,  true,     "String value"
externalId,  string,  false,    "String value"
description, string,  false,    "String value"
enabled,     boolean, true,     "Enabled status'
userGroup,   IRI,     true,     "IRI value of UserGroup"
tagsData,    json,    false,    "An object with Tag Groups IRI with arrays of Tags IRI"
publicIpV4,  string,  false,    "String value'
publicIpV6,  string,  false,    "String value'
gatewayIpV4, string,  false,    "String value'
gatewayIpV6, string,  false,    "String value'
ssh,         string,  false,    "String value'
comment,     string,  false,    "String value'

|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::post_collection_management_rules.csv[]
|===

==== Messages

[cols=",~",format="csv",options="header"]
|===
ID, Content
include::post_collection_messages.csv[]
|===


=== Read / Get Collection

==== Description
Retrieve a list of Network
/api/networks, method=Get

==== Request Parameters

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type,    Required, Comment
page,       number,  false,    "Page index, from 0"
limit,      number,  false,    "Items per page"
name,       string,  false,    "Filter by 'deviceDiagnostic.name LIKE %name%'"
createdAt,  date,    false,    "Search on date of creation"
updatedAt,  date,    false,    "Search on date of update"
enabled,    boolean, false,    "Filter on enabled status"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_collection_management_rules.csv[]
|===

=== Read / Get Item

==== Description
Retrieve a Network
/api/networks/{code}, method=Get

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===


==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::get_item_management_rules.csv[]
|===


=== Patch

==== Description
/api/networks/{code}, method=Patch

===== Body Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,    Type,    Required, Comment
name,        string,  true,     "String value"
externalId,  string,  false,    "String value"
description, string,  false,    "String value"
enabled,     boolean, true,     "Enabled status'
userGroup,   IRI,     true,     "IRI value of UserGroup"
tagsData,    json,    false,    "An object with Tag Groups IRI with arrays of Tags IRI"
publicIpV4,  string,  false,    "String value'
publicIpV6,  string,  false,    "String value'
gatewayIpV4, string,  false,    "String value'
gatewayIpV6, string,  false,    "String value'
ssh,         string,  false,    "String value'
comment,     string,  false,    "String value'
|===

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_management_rules.csv[]
|===

<<<

=== Patch enable

==== Description
/api/networks/{code}/enable, method=Patch


[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_enable_management_rules.csv[]
|===

<<<

=== Patch disable

==== Description
/api/networks/{code}/disable, method=Patch

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_enable_management_rules.csv[]
|===

<<<

=== Patch name

==== Description
/api/networks/{code}/name, method=Patch

===== Body Data (json)
At least one of the fields must be provided.
[cols=",,,~",format="csv",options="header"]
|===
Property, Type, Required, Comment
name, string, false, "String value"
description, string, false, "String value"

|===

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::patch_enable_management_rules.csv[]
|===

<<<


=== Update / Put Item

==== Description
Update a Network
/api/networks/{code}, method=Put

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

===== Put Data (json)

[cols=",,,~",format="csv",options="header"]
|===
Property,    Type,    Required, Comment
name,        string,  true,     "String value"
externalId,  string,  false,    "String value"
description, string,  false,    "String value"
enabled,     boolean, false,    "Enabled status, default to true"
userGroup,   IRI,     true,     "IRI value of UserGroup"
tagsData,    json,    false,    "An object with Tag Groups IRI with arrays of Tags IRI"
publicIpV4,  string,  false,    "String value'
publicIpV6,  string,  false,    "String value'
gatewayIpV4, string,  false,    "String value'
gatewayIpV6, string,  false,    "String value'
ssh,         string,  false,    "String value'
comment,     string,  false,    "String value'
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::put_item_management_rules.csv[]
|===

=== Delete / Delete Item

==== Description
Delete a Network
/api/networks/{code}, method=Delete

==== Path Parameter

[cols=",,,~",format="csv",options="header"]
|===
Parameters, Type, Required, Comment
code, string, true, "uuid"
|===

==== Management rules

[cols=",,,~",format="csv",options="header"]
|===
ID, Added, Expired, Description
include::delete_item_management_rules.csv[]
|===
